FROM almalinux:9
ARG course="aws with devops" \
    trainer="sivakumar" \
    duration="120hrs"
RUN echo "course:$course  trainer:$trainer  duration:$duration"
ENV course=$course
ENV trainer=$trainer 
CMD ["sleep","200"]